/** Granular permissions — use with hasPermission(), not hard-coded role checks. */
export const PERMISSIONS = {
  // Clients
  CLIENT_VIEW: "client.view",
  CLIENT_CREATE: "client.create",
  CLIENT_EDIT: "client.edit",
  // Assessment
  ASSESSMENT_VIEW: "assessment.view",
  ASSESSMENT_CREATE: "assessment.create",
  ASSESSMENT_EDIT: "assessment.edit",
  // Program
  PROGRAM_VIEW: "program.view",
  PROGRAM_CREATE: "program.create",
  PROGRAM_EDIT: "program.edit",
  PROGRAM_PUBLISH: "program.publish",
  // Session
  SESSION_VIEW: "session.view",
  SESSION_START: "session.start",
  SESSION_LOG: "session.log",
  SESSION_EDIT: "session.edit",
  // Progress & nutrition
  PROGRESS_VIEW: "progress.view",
  PROGRESS_EDIT: "progress.edit",
  NUTRITION_VIEW: "nutrition.view",
  NUTRITION_EDIT: "nutrition.edit",
  // Communication
  MESSAGE_CLIENT: "message.client",
  // Leads & sales
  LEAD_VIEW: "lead.view",
  LEAD_CREATE: "lead.create",
  CONSULTATION_CREATE: "consultation.create",
  CONSULTATION_VIEW: "consultation.view",
  // Revenue
  OWN_REVENUE_VIEW: "own.revenue.view",
  ORG_REVENUE_VIEW: "org.revenue.view",
  // Admin
  TRAINER_MANAGE: "trainer.manage",
  USER_MANAGE: "user.manage",
  ROLE_MANAGE: "role.manage",
  ORG_SETTINGS: "org.settings",
  ANALYTICS_VIEW: "analytics.view",
  AUDIT_VIEW: "audit.view",
  // Development
  COACH_DEVELOPMENT: "coach.development",
  // Calendar
  CALENDAR_VIEW: "calendar.view",
  CALENDAR_EDIT: "calendar.edit",
  // Operations
  WORK_REQUEST_VIEW: "work_request.view",
  WORK_REQUEST_CREATE: "work_request.create",
  WORK_REQUEST_APPROVE: "work_request.approve",
  // Attendance (client)
  ATTENDANCE_VIEW: "attendance.view",
  ATTENDANCE_WRITE: "attendance.write",
  // Coach match (client)
  COACH_MATCH: "coach.match",
  // Community + commerce
  PARTNER_VIEW: "partner.view",
  PARTNER_MANAGE: "partner.manage",
  COMMUNITY_VIEW: "community.view",
  COMMUNITY_MANAGE: "community.manage",
  MODERATION_VIEW: "moderation.view",
  MODERATION_MANAGE: "moderation.manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export type AppRole = "admin" | "centre_manager" | "trainer" | "client";

const TRAINER_PERMISSIONS: Permission[] = [
  PERMISSIONS.CLIENT_VIEW,
  PERMISSIONS.CLIENT_CREATE,
  PERMISSIONS.CLIENT_EDIT,
  PERMISSIONS.ASSESSMENT_VIEW,
  PERMISSIONS.ASSESSMENT_CREATE,
  PERMISSIONS.ASSESSMENT_EDIT,
  PERMISSIONS.PROGRAM_VIEW,
  PERMISSIONS.PROGRAM_CREATE,
  PERMISSIONS.PROGRAM_EDIT,
  PERMISSIONS.PROGRAM_PUBLISH,
  PERMISSIONS.SESSION_VIEW,
  PERMISSIONS.SESSION_START,
  PERMISSIONS.SESSION_LOG,
  PERMISSIONS.SESSION_EDIT,
  PERMISSIONS.PROGRESS_VIEW,
  PERMISSIONS.PROGRESS_EDIT,
  PERMISSIONS.NUTRITION_VIEW,
  PERMISSIONS.NUTRITION_EDIT,
  PERMISSIONS.MESSAGE_CLIENT,
  PERMISSIONS.LEAD_VIEW,
  PERMISSIONS.LEAD_CREATE,
  PERMISSIONS.CONSULTATION_CREATE,
  PERMISSIONS.CONSULTATION_VIEW,
  PERMISSIONS.CALENDAR_VIEW,
  PERMISSIONS.CALENDAR_EDIT,
  PERMISSIONS.COACH_DEVELOPMENT,
  PERMISSIONS.OWN_REVENUE_VIEW,
  PERMISSIONS.WORK_REQUEST_VIEW,
  PERMISSIONS.WORK_REQUEST_CREATE,
  PERMISSIONS.PARTNER_VIEW,
  PERMISSIONS.COMMUNITY_VIEW,
  PERMISSIONS.COMMUNITY_MANAGE,
];

const CLIENT_PERMISSIONS: Permission[] = [
  PERMISSIONS.PROGRAM_VIEW,
  PERMISSIONS.SESSION_VIEW,
  PERMISSIONS.ASSESSMENT_VIEW,
  PERMISSIONS.PROGRESS_VIEW,
  PERMISSIONS.NUTRITION_VIEW,
  PERMISSIONS.ATTENDANCE_VIEW,
  PERMISSIONS.ATTENDANCE_WRITE,
  PERMISSIONS.COACH_MATCH,
  PERMISSIONS.MESSAGE_CLIENT,
  PERMISSIONS.PARTNER_VIEW,
  PERMISSIONS.COMMUNITY_VIEW,
];

const ADMIN_PERMISSIONS: Permission[] = [
  ...Object.values(PERMISSIONS),
];

const CENTRE_MANAGER_PERMISSIONS: Permission[] = [
  PERMISSIONS.CLIENT_VIEW,
  PERMISSIONS.LEAD_VIEW,
  PERMISSIONS.LEAD_CREATE,
  PERMISSIONS.CONSULTATION_VIEW,
  PERMISSIONS.CONSULTATION_CREATE,
  PERMISSIONS.ANALYTICS_VIEW,
  PERMISSIONS.TRAINER_MANAGE,
  PERMISSIONS.OWN_REVENUE_VIEW,
  PERMISSIONS.ORG_SETTINGS,
  PERMISSIONS.ORG_REVENUE_VIEW,
  PERMISSIONS.CLIENT_CREATE,
  PERMISSIONS.CLIENT_EDIT,
  PERMISSIONS.AUDIT_VIEW,
  PERMISSIONS.USER_MANAGE,
  PERMISSIONS.WORK_REQUEST_VIEW,
  PERMISSIONS.WORK_REQUEST_CREATE,
  PERMISSIONS.WORK_REQUEST_APPROVE,
  PERMISSIONS.SESSION_VIEW,
  PERMISSIONS.PARTNER_VIEW,
  PERMISSIONS.PARTNER_MANAGE,
  PERMISSIONS.COMMUNITY_VIEW,
  PERMISSIONS.COMMUNITY_MANAGE,
  PERMISSIONS.MODERATION_VIEW,
  PERMISSIONS.MODERATION_MANAGE,
];

export const ROLE_PERMISSIONS: Record<AppRole, Permission[]> = {
  admin: ADMIN_PERMISSIONS,
  centre_manager: CENTRE_MANAGER_PERMISSIONS,
  trainer: TRAINER_PERMISSIONS,
  client: CLIENT_PERMISSIONS,
};

/** Maps route modules to required permission */
export const MODULE_PERMISSION: Record<string, Permission> = {
  dashboard: PERMISSIONS.CLIENT_VIEW,
  calendar: PERMISSIONS.CALENDAR_VIEW,
  clients: PERMISSIONS.CLIENT_VIEW,
  programs: PERMISSIONS.PROGRAM_VIEW,
  sessions: PERMISSIONS.SESSION_VIEW,
  progress: PERMISSIONS.PROGRESS_VIEW,
  leads: PERMISSIONS.LEAD_VIEW,
  money: PERMISSIONS.OWN_REVENUE_VIEW,
  me: PERMISSIONS.CLIENT_VIEW,
  tasks: PERMISSIONS.CALENDAR_VIEW,
  development: PERMISSIONS.COACH_DEVELOPMENT,
  // Admin
  analytics: PERMISSIONS.ANALYTICS_VIEW,
  trainers: PERMISSIONS.TRAINER_MANAGE,
  staff: PERMISSIONS.TRAINER_MANAGE,
  assets: PERMISSIONS.ORG_SETTINGS,
  inventory: PERMISSIONS.ORG_SETTINGS,
  "work-requests": PERMISSIONS.WORK_REQUEST_VIEW,
  organisation: PERMISSIONS.ORG_SETTINGS,
  audit: PERMISSIONS.AUDIT_VIEW,
  memberships: PERMISSIONS.ORG_REVENUE_VIEW,
  payments: PERMISSIONS.ORG_REVENUE_VIEW,
  reports: PERMISSIONS.ANALYTICS_VIEW,
  // Client
  home: PERMISSIONS.PROGRAM_VIEW,
  overview: PERMISSIONS.PROGRAM_VIEW,
  programmes: PERMISSIONS.PROGRAM_VIEW,
  workout: PERMISSIONS.PROGRAM_VIEW,
  nutrition: PERMISSIONS.NUTRITION_VIEW,
  messages: PERMISSIONS.MESSAGE_CLIENT,
  schedule: PERMISSIONS.SESSION_VIEW,
  profile: PERMISSIONS.PROGRAM_VIEW,
  assessments: PERMISSIONS.ASSESSMENT_VIEW,
  attendance: PERMISSIONS.ATTENDANCE_VIEW,
  "coach-match": PERMISSIONS.COACH_MATCH,
  community: PERMISSIONS.COMMUNITY_VIEW,
  partners: PERMISSIONS.PARTNER_MANAGE,
  moderation: PERMISSIONS.MODERATION_VIEW,
  // Legacy redirects
  schedule_legacy: PERMISSIONS.CALENDAR_VIEW,
  members: PERMISSIONS.CLIENT_VIEW,
  onboarding: PERMISSIONS.CLIENT_VIEW,
  "close-os": PERMISSIONS.CONSULTATION_CREATE,
  "coach-mirror": PERMISSIONS.COACH_DEVELOPMENT,
  "coach-pro": PERMISSIONS.PROGRAM_CREATE,
  "ai-coach": PERMISSIONS.MESSAGE_CLIENT,
  "workout-planner": PERMISSIONS.PROGRAM_CREATE,
};
